# Generated by Django 5.2.7 on 2026-04-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeaSide_Shop', '0009_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('cod', 'Pending/COD'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Cancelled')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='sslcommerz_session_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_reduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='validation_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('sslcommerz', 'Pay Online with SSLCommerz')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('canceled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
